 3   NU_ANO : Ano_Notificcao
 4   SG_UF_NOT : Sigla_UF_Notificacao   
 5   ID_MUNICIP : Codigo_Municipio
 6   ID_REGIONA : Codigo_Regiao
 7   DT_DIAG : Data_Diagnostico
 8   ANO_NASC : Ano_Nascimento    
 9   NU_IDADE_N : Idade_Valor_Unidade 
 10  CS_SEXO : Paciente_Sexo
 11  CS_GESTANT : Paciente_Gestante
 12  CS_RACA : Paciente_Raca
 13  CS_ESCOL_N : Paciente_Escolaridade
 14  SG_UF : UF_Residente       
 15  ID_MN_RESI : Codigo_Municipio
 16  ID_RG_RESI : Codigo_Regiao
 17  ID_PAIS : Codigo_Pais
 18  NDUPLIC_N : Duplicidade
 19  IN_VINCULA : Caso_Vinculado  
 20  DT_DIGITA : Data_Digitacao
 21  DT_TRANSUS : Data_Transferencia_Unidade_Saude
 22  DT_TRANSDM : Data_Tranferencia_Distrito_Municipal
 23  DT_TRANSSM : Data_Transferencia_Secretaria_Municipal
 24  DT_TRANSRM : Data_Transferencia_Regional_Municipal  
 25  DT_TRANSRS : Data_Transferencia_Regional_Saude  
 26  DT_TRANSSE : Data_Transferencia_Secretaria_Estadual_Saude  
 27  CS_FLXRET : Fluxo_Retorno   
 28  FLXRECEBI : Recebido_Fluxo_Retorno   
 29  MIGRADO_W : Origem_Migracao   
 30  ID_OCUPA_N : Ocupacao_Codificada  
 31  TRATAMENTO : Tipo_Tratamento 
 32  INSTITUCIO : Institucionalizado   
 33  RAIOX_TORA : RaioX_Torax  
 34  TESTE_TUBE : Teste_Tuberculineo  
 35  FORMA : Forma_Clinica_Tuberculose       
 36  EXTRAPU1_N --  
 37  EXTRAPU2_N --
 38  EXTRAPUL_O --
 39  AGRAVAIDS : Comorbidade_AIDS   
 40  AGRAVALCOO : Comorbidade_Alcoolismo  
 41  AGRAVDIABE : Comorbidade_Diabetes  
 42  AGRAVDOENC : Comorbidade_Doenca  
 43  AGRAVOUTRA : Comorbidade_Outra  
 44  AGRAVOUTDE : Comorbidade_Especifique 
 45  BACILOSC_E : Baciloscopia_Escarro1
 46  BACILOS_E2 : Baciloscopia_Escarro2
 47  BACILOSC_O : Baciloscopia_OutroMaterial
 48  CULTURA_ES : Cultura_Escarro
 49  CULTURA_OU : Cultura_Outros
 50  HIV            
 51  HISTOPATOL : Histopatologia 
 52  DT_INIC_TR : Data_Inicio_Tratamento 
 53  RIFAMPICIN : Medicamentos_TB_Rifampicina
 54  ISONIAZIDA : Medicamentos_Isoniazida  
 55  ETAMBUTOL : Medicamentos_Etambutol   
 56  ESTREPTOMI : Medicamentos_Estreptomicina 
 57  PIRAZINAMI : Medicamentos_Pirazinamida 
 58  ETIONAMIDA : Medicamentos_Etionamida 
 59  OUTRAS : Medicamentos_Outros      
 60  OUTRAS_DES : Medicamentos_Outros_Descricao  
 61  TRAT_SUPER : Tratamento_Supervisionado  
 62  NU_CONTATO : Numero_Contato  
 63  DOENCA_TRA : Doenca_Tratamento_Especial  
 64  SG_UF_AT : UF_Atendimento_Atual    
 65  ID_MUNIC_A : Municipio_Atendimento_Atual  
 66  DT_NOTI_AT : Data_Notificacao_Atual  
 67  SG_UF_2 : UF_Residencia_Atual     
 68  ID_MUNIC_2 : Municipio_Residencia_Atual  
 69  BACILOSC_1 : Baciloscopia_1Mes 
 70  BACILOSC_2 : Baciloscopia_2Mes 
 71  BACILOSC_3 : Baciloscopia_3Mes 
 72  BACILOSC_4 : Baciloscopia_4Mes 
 73  BACILOSC_5 : Baciloscopia_5Mes 
 74  BACILOSC_6 : Baciloscopia_6Mes  
 75  TRATSUP_AT : Trat_Supervisionado_Atual  
 76  DT_MUDANCA : Data_Mudanca_Tratamento
 77  NU_COMU_EX : Contatos_Examinados 
 78  SITUA_9_M : Situacao_9_Meses   
 79  SITUA_12_M : Situacao_12_Meses  
 80  SITUA_ENCE : Situacao_Encerramento  
 81  DT_ENCERRA : Data_Encerramento  
 82  TPUNINOT : Tipo_Unidade_Notificadora    
 83  POP_LIBER : Populacao_Prisioneira   
 84  POP_RUA : Populacao_Rua     
 85  POP_SAUDE : Populacao_Saude   
 86  POP_IMIG : Pop_Imigrantes
 87  BENEF_GOV : Beneficiario_Programa   
 88  AGRAVDROGA : Comorbidade_Drogas  
 89  AGRAVTABAC : Comorbidade_Tabaco  
 90  TEST_MOLEC : Teste_Molecular  
 91  TEST_SENSI : Teste_Sensibilidade  
 92  ANT_RETRO : Terapia_Antirretroviral   
 93  BAC_APOS_6 : Baciloscopia_Apos_6Meses
 94  TRANSF      
 95  UF_TRANSF   
 96  MUN_TRANSF